sudo: false
dist: trusty
language: node_js
node_js:
  - "4.1"
cache:
  directories:
    - node_modules
install:
  - npm install -g gitbook-cli
  - npm install -g npm-registry-client
script:
  - make
after_script:
- test $TRAVIS_TEST_RESULT == "0" && test $TRAVIS_PULL_REQUEST == "false" && test
  $TRAVIS_BRANCH == "master" && make install
